### ISSUE TITLE
Hello Example Question

### ISSUE THREAD

**Issue by sapeurrr** [SpinQTech/SpinQit#1]
When I try your hello example, it shows that "DLL load failed while importing spinq_backends". Then I go check the code, I find there is no package under spinqit named "spinq_backends".  You have "from spinqit.spinq_backends import BasicSimulator" in basic_simulator_backend.py under "backend" package.

**Comment by SpinQTech** [comment]
Hi,

Do you run the example from your IDE? If so, you need to configure the library path in your IDE. On Windows, the system environment variable should be PATH. Could you please try running this example under Python prompt? BTW, in the site-packages/spinqit directory, there should be a spinq_backends.yourplatform.pyd or spinq_backends.yourplatform.so file.

**Comment by sapeurrr** [comment]
Thanks, find it.
