### ISSUE TITLE
python包挺好用的，学习了很多！另一方面，问题也很多。先问最关心的一个。

### ISSUE THREAD

**Issue by musicfish1973** [SpinQTech/SpinQit#2]
如何体现出量子优势？比如qnn_example.py这个程序，在我的win10上能跑，那如何在量子计算机上跑呢？如何体现量子计算机的优势呢？

**Comment by musicfish1973** [comment]
云平台上跑了个hello程序（就是非常慢，没体现出量子优势），如何在上面跑qnn_example.py呢？

**Comment by SpinQTech** [comment]
你好，感谢使用，SpinQit的程序可以提交到本地量子计算机或云平台。本地量子计算机需要购买。量子计算目前需要在一定问题一定规模以上才能看到明显的优势，目前我们云平台上提供的免费量子计算机只供体验使用，还不能看到量子优势。qnn_example.py目前还不能提交到云平台执行，因为我们目前云上资源较少，而这个程序会占用较长时间。
